services:
  - type: web
    name: jallal-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_render.py
    healthCheckPath: /wh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
